Models/Equipe.cs
using System;
using System.Collections.Generic;
using System.IO;
using ProjetoEplayers.Interface;

namespace ProjetoEplayers.Models {
    public class Equipe : EPlayersBase, IEquipe {
        public int IdEquipe { get; set; }
        public string Nome { get; set; }
        public string Imagem { get; set; }

        private const string PATH = "Database/Equipe.csv";

        public Equipe () {
            CreateFolderAndFile (PATH);
        }
        public void Create (Equipe e) {
            string[] linhas = { PrepararLinha (e) };
            File.AppendAllLines (PATH, linhas);
        }

        private string PrepararLinha (Equipe _e) {
            return $"{_e.IdEquipe};{_e.Nome};{_e.Imagem}";
        }

        public void Delete (int IdEquipe) {
            List<string> linhas = ReadAllLinesCSV (PATH);
            linhas.RemoveAll (y => y.Split (";") [0] == IdEquipe.ToString ());
            RewriteCSV (PATH, linhas);
        }

        public List<Equipe> ReadAll () {
            List<Equipe> equipes = new List<Equipe> ();
            string[] linhas = File.ReadAllLines (PATH);
            foreach (var item in linhas) {
                string[] linha = item.Split (";");
                Equipe equipe = new Equipe ();
                equipe.IdEquipe = Int32.Parse (linha[0]);
                equipe.Nome = linha[1];
                equipe.Imagem = linha[2];

                equipes.Add (equipe);
            }
            return equipes;
        }

        public void Update (Equipe e) {
            List<string> linhas = ReadAllLinesCSV (PATH);
            linhas.RemoveAll (y => y.Split (";") [0] == e.IdEquipe.ToString ());
            linhas.Add (PrepararLinha (e));
            RewriteCSV (PATH, linhas);
        }
    }
}

Controllers/EquipeController.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjetoEplayers.Models;

namespace ProjetoEplayers.Controllers

{
    public class EquipeController : Controller {
        Equipe equipeModel = new Equipe ();
        public IActionResult Index () {
            ViewBag.Equipes = equipeModel.ReadAll ();
            return View ();
        }
        public IActionResult Cadastrar (IFormCollection form) {
            Equipe equipe = new Equipe ();
            equipe.IdEquipe = Int32.Parse (form["IdEquipe"]);
            equipe.Nome = form["Nome"];

            //Upload da imagem
            var file = form.Files[0];
            //patasA, pastaB, pastaC, arquivo.PDF
            //patasA/pastaB/pastaC/arquivo.PDF
            var folder = Path.Combine (Directory.GetCurrentDirectory (), "wwwroot/img/Equipes");

            if (file != null) {
                if (!Directory.Exists (folder)) {
                    Directory.CreateDirectory (folder);
                }

                var path = Path.Combine (Directory.GetCurrentDirectory (), "wwwroot/img/", folder, file.FileName);
                using (var stream = new FileStream (path, FileMode.Create)) {
                    file.CopyTo (stream);
                }
                equipe.Imagem = file.FileName;
            } else {
                equipe.Imagem = "padrao.png";
            }

            //Fim do upload Imagem

            equipeModel.Create (equipe);

            return LocalRedirect ("~/Equipe");

        }

        [Route ("Equipe/{id}")]
        public IActionResult Excluir (int id) {
            equipeModel.Delete (id);
            return LocalRedirect ("~/Equipe");
        }
    }
}

Views/Equipe/index.cshtml
@model Equipe
@{
    ViewData["Title"] =  "Equipes";
}

<div class="titulo_pagina">
            <h1>cadastro de  @ViewData["Title"]</h1>
        </div>

<form class="cadastro" action="@Url.Action("Cadastrar")" method="post" enctype="multipart/form-data">

<div class="campo">
<label for="IdEquipe">IdEquipe</label>
<input type="text" name= "IdEquipe" id="IdEquipe">
</div>

<div class="campo">
<label for="Nome">Nome</label>
<input type="text" name= "Nome" id="Nome">
</div>

<div class="campo">
<label for="Imagem">Imagem</label>
<input type="file" name= "Imagem" id="Imagem">
</div>

<button class="gradient btn" type="submit">Cadastrar</button>
</form>

<table class="table table-responsive table-striped">
    <thead>
        <th>Id</th>
        <th>Nome</th>
        <th>Imagem</th>
        <th>Ações</th>
    </thead>
    <tbody>

        @foreach(var item in ViewBag.Equipes)
        {
            <tr>
                <td>@item.IdEquipe</td>
                <td>@item.Nome</td>
                <td><img src="img/Equipes/@item.Imagem" alt="Imagem do time @item.Nome" ></td>
                <td>
                    <a asp-controller="Equipe" asp-action="Excluir" asp-route-id="@item.IdEquipe">
                        <i class="fas fa-trash"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>